swagger: "2.0"
info:
  description: Generate images and videos with replicate.com
  title: replicate
  version: "1.0"
  x-direktiv-meta:
    container: gcr.io/direktiv/functions/replicate
    maintainer: |-
      [direktiv.io](https://www.direktiv.io) 
    issues: https://github.com/direktiv-apps/replicate/issues
    url: https://github.com/direktiv-apps/replicate  
    categories:
    - misc
    license: |-
      [Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0)
    long-description: >-
      This function can call the [replicate.com](https://replicate.com) API to generate images and videos with AI. 
consumes:
- application/json
produces:
- application/json
schemes:
- http
paths:
  /: 
    delete:
      parameters:
        - name: Direktiv-ActionID
          in: header
          type: string
          description: |
            On cancel Direktiv sends a DELETE request to
            the action with id in the header
      x-direktiv:
        cancel: echo 'cancel {{ .DirektivActionID }}'
      responses:
        200:
    post:
      parameters:
        - name: Direktiv-ActionID
          in: header
          type: string
          default: development
          description: |
            direktiv action id is an UUID. 
            For development it can be set to 'development'
        - name: Direktiv-TempDir
          in: header
          type: string
          default: /tmp
          description: |
            direktiv temp dir is the working directory for that request
            For development it can be set to e.g. '/tmp'
        - name: body
          in: body
          schema:
            type: object
            required: ["api-key", "model", "version"]
            properties:
              debug:
                type: boolean
                description: Print debug output
              api-key:
                type: string
                description: API key provided by replicate.com
              model:
                type: string
                description: Model for generation
                example: stability-ai/stable-diffusion
              version:
                type: string
                description: Model version
              input:
                type: object
                additionalProperties: {}
              files:
                type: array
                items:
                  type: object
                  required: ["name", "mime", "file"]
                  properties:
                    name:
                      type: string
                      description: Name of the parameter in replicate.com API for the model
                    mime:
                      type: string
                      description: Mimetype of the file
                      example: image/png
                    file:
                      type: string
                      description: Path to the file provided by Direktiv
      # direktiv code generation is configured here
      x-direktiv-function: |-
        functions:
        - id: replicate
          image: gcr.io/direktiv/functions/replicate:1.0
          type: knative-workflow
      x-direktiv-examples:
        # ADD MORE EXAMPLES HERE
        - title: Basic
          content: |-
            - id: replicate
              type: action
              action:
                function: replicate
                secrets: ["replicate"]
                input:
                  debug: true 
                  model: stability-ai/stable-diffusion
                  version: f178fa7a1ae43a9a9af01b833b9d2ecf97b1bcb0acfd2dc5dd04895e042863f1
                  api-key: jq(.secrets.replicate)
                  input:
                    prompt: an green elephant jumping of a bridge with a parachute 
        - title: Advanced
          content: |-
            - id: replicate
              type: action
              action:
                function: replicate
                input: 
                  secrets: ["replicate"]
                  model: lambdal/text-to-pokemon
                  version: 3554d9e699e09693d3fa334a79c58be9a405dd021d3e11281256d53185868912
                  input:
                    one: two
                    three: four
                    six: 6
                  files:
                  - name: test
                    mime: image/png
                    file: "/tests/in.png"
              catch:
              - error: "*"
      x-direktiv-secrets:
        - name: apikey
          description: Replicate.com API key
      x-direktiv:  
        cmds:
        - action: http
          debug: '{{ .Debug }}'
          url: https://api.replicate.com/v1/predictions
          method: POST
          headers: 
          - Content-Type: application/json
          - Authorization: 'Token {{ .Body.APIKey }}'
          data:   
            kind: string
            value: |
              { 
                "model": "{{ .Model }}",
                "version":  "{{ .Version }}",
                "input": {
                  {{- $first := true}}
                  {{- range $k, $v := .Input }}
                    {{- if $first}}
                      {{- $first = false}}
                    {{- else}},{{- end}}
                    "{{ $k }}" : {{ $v | toJson }}  
                  {{- end}}
                  {{ $length := len .Files }} {{ if gt $length 0 }}
                  {{range $i, $a := .Files }}
                    ,
                    "{{ ($a).Name  }}":  "data:{{ ($a).Mime }};base64,{{ ($a).File | file64 }}"
                  {{ end }}
                  {{ end }}
                }
              }
        output: |
          {
            "replicate": {{ index (index . 0) "result" | toJson }}
          }
      x-direktiv-errors:
        io.direktiv.command.error: Command execution failed
        io.direktiv.output.error: Template error for output generation of the service
        io.direktiv.ri.error: Can not create information object from request
      responses:
        200:
          description: List of executed commands.
          examples:
            replicate:
              completed_at:
              created_at: '2023-02-10T09:28:22.977673Z'
              error:
              id: qzk7dr2zjjasdsdsadada2ja4mmea
              input:
                num_outputs: 1
                prompt: a golden horse
              logs: ''
              metrics: {}
              output:
              started_at:
              status: starting
              urls:
                cancel: https://api.replicate.com/v1/predictions/qzk7dr2zjjasdsdsadada2ja4mmea/cancel
                get: https://api.replicate.com/v1/predictions/qzk7dr2zjjasdsdsadada2ja4mmea
              version: 3554d9e699e09693d3fa334a79c58be9a405dd021d3e11281256d53185868912
              webhook_completed:
          schema:
            type: object
            additionalProperties: {}
        default:
          description: generic error response
          headers:
            Direktiv-ErrorCode:
              type: string
            Direktiv-ErrorMessage:
              type: string
          schema:
            $ref: "#/definitions/error"
definitions:
  direktivFile:
    type: object
    x-go-type:
      type: DirektivFile
      import:
        package: github.com/direktiv/apps/go/pkg/apps 
  error:
    type: object
    required:
      - errorCode
      - errorMessage
    properties:
      errorCode:
        type: string
      errorMessage:
        type: string
